/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ec.alpha.utilidad;

/**
 *
 * @author ppltm
 */
public class Info {
    
public static String privateStringKey = "-----BEGIN PRIVATE KEY-----\n" +
"MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDMiLZ8UU2Eii+k\n" +
"Zct1UaxE1JaqbfctqEchQlWkfOeNwnwlztTjA06dgDW8M7rHmg3uf1eTWqOV9BS5\n" +
"JsagESI2vqQd0YTdjccOQKbt8ZrFveGxxEXWbP4J0RAqGnpJI4Qf7xsIpFcZaiQF\n" +
"NjGqJ7IyYKrlz8n7B2DjxcUCgD/aTttqpS/nH4oL17+yN5wjT4bTzNBnNXR8vUq9\n" +
"eoGmK+XNRmklmhiOVT/g+nPkTcCUI78cPv4jYF+xXmVrwDlQ90G888k+dG0ixH5X\n" +
"pqummcg89v7HvHOm3G8KW9tvPteNNjZckRpyk/9xf1MGCIuxFyWd5jD+iwzBCz7E\n" +
"S+0KhsjpAgMBAAECggEBAIp2KoNyTrXhDmuOdfPP/H0EJZLuqpyABNchHvUhkWfI\n" +
"N18o67larce12aq0okcppTDFiDW68G89MyI8e840iyLgYB3HjtileBHP9rGyE4K2\n" +
"DqnXIygL1NY0b2rxTcNhhbpQlc594nDUB9p3W5vDD8FG66pzxlpoHlFTuxD8XT2d\n" +
"WVJkLicrVM1bA378A/hU297M5VHvJarrd2LiELoBpVPzRoSAbXc0p8q28JwOz6mD\n" +
"EkWaydUuycXaYs2SRYVZPSw09midYYAs85cODdTehbYqw8cuDsjDe8R8q+2QstQc\n" +
"nYdYCvkpb6geWlAPL4fXyRgDrCx4qOPjEMUr2Kf0ZwECgYEA/Ogyq8cpXWEtrjfE\n" +
"HViBPWzVVN/lnO8WHpVt+b0PTVGelPil+dd0sMh5zimGyx5iv6uUMgB4nKykR9Wh\n" +
"fbLWIl38KiGVt6mmICvdqUKrDiqO09sIvEf0U8gBcIG2mzle5KaG7bkwxJNOqjgk\n" +
"rHMu+7H9l5CidNsvZnfme3GB03kCgYEAzwkRj/UdfiBL3vFscz0BJ89nE8OqUh+K\n" +
"MV7kVopc9coLuyhJLDUJKezIjDstvSz81fuzDVEHUbYf6M0Ou0v4F/ExywDT/LnV\n" +
"m3BWSAruYJV6y00rPXcPIgiXU0q0myldPFasMCf/65x6qlBMl3pWEZ5gP7DKrzTO\n" +
"gxJJdZeDVPECgYEAjcOao6+AAFf4wy9/PvPdfhEDhA/9JXrfa0VX4CWZ7j1SJy85\n" +
"2lJrlqzJmkasyC7AK7CB4YViFnCvpZSacVtNrPYB45vv0IPIG0B7f+Ve/RHd/eNJ\n" +
"gkDTNCNoqygKs/f0uTafa6HjNE1eSwwtgn0OWQfsnoj0h4xVhZqwF4IIxAECgYAC\n" +
"mZON4j8fkVpCj3eULuTv0gvyVJez9k9u9UkayRwHviTNkeDxXC0kSKPwFuIpKQJ3\n" +
"0XRbK3RTE11tN/4CXh7cdhvw966x0sea7xs2RmTd86KaIPr1B6S6Aa+czShddnSE\n" +
"SHZbGHV/SPTFZMLBeDjSedGtmxPAhYI+ZSFlB6UPkQKBgCu0kwmWBv57YgMgf5VL\n" +
"M/bjRrnJcPCSBDnzTkuMr+zS+79U4SlcthSMESzcYVwtb1XYSGJTMNeS9bTigcUw\n" +
"FZ4YnVSKXDjISLCmhwRXA09Xw9pyUUytLMQpi9Uqsy94EXxeDYjOx7fMmwGmMzw9\n" +
"nfQBtDC43TUervoQgo3hbiXn\n" +
"-----END PRIVATE KEY-----";


public static String cerficado =  "-----BEGIN CERTIFICATE-----\n" +
"MIIHIjCCBgqgAwIBAgIQAfWeKNfuGlT/e7VQgP7E2DANBgkqhkiG9w0BAQsFADCB\n" +
"jDELMAkGA1UEBhMCRUMxEjAQBgNVBAgTCVBpY2hpbmNoYTEOMAwGA1UEBxMFUXVp\n" +
"dG8xJjAkBgNVBAoTHUFscGhhIFRlY2hub2xvZ2llcyBDaWEuIEx0ZGEuMTEwLwYD\n" +
"VQQDEyhBbHBoYSBUZWNobm9sb2dpZXMgQXRsYXMgU2lnbmluZyBDQSAyMDIzMB4X\n" +
"DTIzMDcxMTE0MjIyN1oXDTI2MDMyMjAwMDAwMFowRTENMAsGA1UEBRMEMDAwMTEL\n" +
"MAkGA1UEBhMCRUMxJzAlBgNVBAMMHnN0ZXZlbi5jaGlyaWJvZ2FAYWxwaGFzaWRl\n" +
"LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMyItnxRTYSKL6Rl\n" +
"y3VRrETUlqpt9y2oRyFCVaR8543CfCXO1OMDTp2ANbwzuseaDe5/V5Nao5X0FLkm\n" +
"xqARIja+pB3RhN2Nxw5Apu3xmsW94bHERdZs/gnRECoaekkjhB/vGwikVxlqJAU2\n" +
"MaonsjJgquXPyfsHYOPFxQKAP9pO22qlL+cfigvXv7I3nCNPhtPM0Gc1dHy9Sr16\n" +
"gaYr5c1GaSWaGI5VP+D6c+RNwJQjvxw+/iNgX7FeZWvAOVD3QbzzyT50bSLEflem\n" +
"q6aZyDz2/se8c6bcbwpb228+1402NlyRGnKT/3F/UwYIi7EXJZ3mMP6LDMELPsRL\n" +
"7QqGyOkCAwEAAaOCA8QwggPAMBoGCisGAQQBg7YpAwEEDBYKMTcyMDQ4OTg3OTAZ\n" +
"BgorBgEEAYO2KQMGBAsWCVJlc2VydmFkbzAbBgorBgEEAYO2KQMIBA0WCzA5OTgw\n" +
"NDA5MDg1MBUGCisGAQQBg7YpAwkEBxYFUXVpdG8wLgYKKwYBBAGDtikCAQQgFh5z\n" +
"dGV2ZW4uY2hpcmlib2dhQGFscGhhc2lkZS5jb20wLgYKKwYBBAGDtikCBAQgFh5D\n" +
"ZXJ0aWZpY2FkbyBkZSBQZXJzb25hIE5hdHVyYWwwFwYKKwYBBAGDtikDCgQJFgdF\n" +
"Y3VhZG9yMBwGCisGAQQBg7YpAw0EDhYMMTc0NTY2OTg3MDAxMBMGCisGAQQBg7Yp\n" +
"AxIEBRYDUEZYMB0GCisGAQQBg7YpAwIEDxYNU3RldmVuIERhbmllbDAWBgorBgEE\n" +
"AYO2KQMEBAgWBlRvcnJlczAZBgorBgEEAYO2KQMFBAsWCVJlc2VydmFkbzArBgor\n" +
"BgEEAYO2KQMHBB0WG0RlIGxvcyBjZWRyb3MgeSBwZWRybyBib3R0bzAhBgkrBgEE\n" +
"AYO2KQEEFBYSQWxwaGEgVGVjaG5vbG9naWVzMBkGCisGAQQBg7YpAwMECxYJQ2hp\n" +
"cmlib2dhMA4GA1UdDwEB/wQEAwIFoDAiBgNVHSUBAf8EGDAWBggrBgEFBQcDAgYK\n" +
"KwYBBAGCNwoDDDAdBgNVHQ4EFgQUHnxCUm37V8N8QLO50yWLtY4jsggwXQYDVR0g\n" +
"BFYwVDBSBgorBgEEAYO2KQIBMEQwQgYIKwYBBQUHAgEWNmh0dHBzOi8vd3d3LmFs\n" +
"cGhhc2lkZS5jb20vZG93bmxvYWRzL05vcm1hdGl2YXMvZHBjLnBkZjAMBgNVHRMB\n" +
"Af8EAjAAMIGxBggrBgEFBQcBAQSBpDCBoTBNBggrBgEFBQcwAYZBaHR0cDovL29j\n" +
"c3AuZ2xvYmFsc2lnbi5jb20vY2EvYWxwaGF0ZWNobm9sb2dpZXNhdGxhc3NpZ25p\n" +
"bmdjYTIwMjMwUAYIKwYBBQUHMAKGRGh0dHA6Ly9zZWN1cmUuZ2xvYmFsc2lnbi5j\n" +
"b20vYWxwaGF0ZWNobm9sb2dpZXNhdGxhc3NpZ25pbmdjYTIwMjMuY3J0MB8GA1Ud\n" +
"IwQYMBaAFBnUks/yIy2QleDbCres2UccmPCrMFUGA1UdHwROMEwwSqBIoEaGRGh0\n" +
"dHA6Ly9jcmwuZ2xvYmFsc2lnbi5jb20vY2EvYWxwaGF0ZWNobm9sb2dpZXNhdGxh\n" +
"c3NpZ25pbmdjYTIwMjMuY3JsMA0GCSqGSIb3DQEBCwUAA4IBAQAEISwPGdRxsB8+\n" +
"Z/V2z2FRl9rItPdqZTdIBv6/7MAFU75pR9SodWKOvdQ2j/+9oUpm+z7QSVhZUKlF\n" +
"TAIWkb7ZtWOEehMsYYhX4i7xFIs7tds7nI35pcQ2C1OZf5Yv+HAU/6idb4vWGVBq\n" +
"3ZE46SHtxOUrEhbWn5X0HknLPXitigK3qGOecvmyY0zzMvjInIMSR20N5ioX9lIO\n" +
"DhUtWt2hHWkHG9fajqw5/ysSDPDNEoPV8XGOzlesbuBOSPGmt7wBFRRwAGU1ccB5\n" +
"Z/eJylEe754aYm3N5G5XorN7Trkw9cthdtW3Asfvdkew+kN6JQImy1Thc4rw3YRg\n" +
"DN1SDf+H\n" +
"-----END CERTIFICATE-----";



public static String rootCrt="-----BEGIN CERTIFICATE-----\n" +
"MIID1DCCArygAwIBAgIQflktBZ7VkCzqNyt6dm/4bDANBgkqhkiG9w0BAQsFADCB\n" +
"gzELMAkGA1UEBhMCRUMxEjAQBgNVBAgTCVBpY2hpbmNoYTEOMAwGA1UEBxMFUXVp\n" +
"dG8xJjAkBgNVBAoTHUFscGhhIFRlY2hub2xvZ2llcyBDaWEuIEx0ZGEuMSgwJgYD\n" +
"VQQDEx9BbHBoYSBUZWNobm9sb2dpZXMgUm9vdCBDQSAyMDIzMB4XDTIzMDMyMjAz\n" +
"NTkxMFoXDTMzMDMyMjAwMDAwMFowgYMxCzAJBgNVBAYTAkVDMRIwEAYDVQQIEwlQ\n" +
"aWNoaW5jaGExDjAMBgNVBAcTBVF1aXRvMSYwJAYDVQQKEx1BbHBoYSBUZWNobm9s\n" +
"b2dpZXMgQ2lhLiBMdGRhLjEoMCYGA1UEAxMfQWxwaGEgVGVjaG5vbG9naWVzIFJv\n" +
"b3QgQ0EgMjAyMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMruTcGV\n" +
"tWwJB+zZe3Mw5EEHBgApZuzIF56f+mOwY8WJTlg50O2NpBxdauHnBsNI1Zpmqzvl\n" +
"O469j743p55ENSoJ3/flrFKP6K0LQb0ErpVeMK+rI1DKmAfEFEFnLgBD5s3kGLiL\n" +
"CIcB9YxCnHFYDpOJEuJZFFYtlYDLK4I5QxC2ARArD2syd/lK7aBybbU/H9dSpKqv\n" +
"mvXio00+toboACyAMCrOmwIepVLY83gdlGbdO7yZyOaHkt43ttV9p6yWG/9asquF\n" +
"8M6XJF7FXfNbNALCZVFaUFASNoaRaRzfjuOx/WUNzALqmccUA6q6cxXaQw97lTmU\n" +
"DZjU0zdMVjPYQ5cCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF\n" +
"MAMBAf8wHQYDVR0OBBYEFMlov42cAer8lKdFG8vp9AiHCLz0MA0GCSqGSIb3DQEB\n" +
"CwUAA4IBAQCay9aEGczL3tuHUFWxoMbtWua9Zorkgi5Feksuq7xibsAxgpftolvA\n" +
"sBWxWvCMdnaq1lMad2TsdqtrceW0Yr/SlvDByD0+chNzcMr/dnPHUTn7Wpbc3V/S\n" +
"kAOrA8uHDSQUsfitEpi/qiL6io0IRaDkUMeFeTLwaAkfApKdnrJoZt2YAviSK3Az\n" +
"a00g8U/a6pceZcmMwnOYC/MnTvSS6R7jlPSCOyQcpr63PoqsI2NekeVjpYLHA9na\n" +
"55q5DWFhtnCxFWmKfawTepzVBkrUqrAvn5z+pRJKYxyQXvNSiywabuFsgVMZ96zP\n" +
"G5mGLl1Rv6bTqk1JTY9FLrkJfA3CjAdE\n" +
"-----END CERTIFICATE-----";
public static String intermediateCrt="-----BEGIN CERTIFICATE-----\n" +
"MIIFHTCCBAWgAwIBAgIQflktE2KICwPLE6HJ4SOdejANBgkqhkiG9w0BAQsFADCB\n" +
"gzELMAkGA1UEBhMCRUMxEjAQBgNVBAgTCVBpY2hpbmNoYTEOMAwGA1UEBxMFUXVp\n" +
"dG8xJjAkBgNVBAoTHUFscGhhIFRlY2hub2xvZ2llcyBDaWEuIEx0ZGEuMSgwJgYD\n" +
"VQQDEx9BbHBoYSBUZWNobm9sb2dpZXMgUm9vdCBDQSAyMDIzMB4XDTIzMDMyMjAz\n" +
"NTkyMVoXDTI2MDMyMjAwMDAwMFowgYwxCzAJBgNVBAYTAkVDMRIwEAYDVQQIEwlQ\n" +
"aWNoaW5jaGExDjAMBgNVBAcTBVF1aXRvMSYwJAYDVQQKEx1BbHBoYSBUZWNobm9s\n" +
"b2dpZXMgQ2lhLiBMdGRhLjExMC8GA1UEAxMoQWxwaGEgVGVjaG5vbG9naWVzIEF0\n" +
"bGFzIFNpZ25pbmcgQ0EgMjAyMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n" +
"ggEBAJZSmQZ7dZobm8K9tYRScVf3wNdunckLo42QJpc3C0n1xKsKt7/JkZQOS7Rx\n" +
"mm0lejjsxGH5iFoIDhG9C7r9liCEYJKflra3qQ6BhDwus3Ut/1X9hk1kt277RWW8\n" +
"mUqGBbsK+FaeXrUV+TRg0tENerwWzriRs/IEA7Isg8123bIX4Hvp4j6wgtgkz7yM\n" +
"hi+j3ftMzGKDTrCBeu8Lnojg3Xi4FGc0848v61mzKP4pUXGXJB6Ul6z9t6TYDnY2\n" +
"CgQpcjckwFTG8ysxSkQ/CKWLxDlkOfVSAkNHx+pKcL3IVr9Zf/5l+B2bS1vpZm9k\n" +
"LVuUTZosPhcR1Ghiw3ye0GsHv5sCAwEAAaOCAYAwggF8MA4GA1UdDwEB/wQEAwIB\n" +
"hjApBgNVHSUEIjAgBggrBgEFBQcDAgYIKwYBBQUHAwQGCisGAQQBgjcKAwwwEgYD\n" +
"VR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUGdSSz/IjLZCV4NsKt6zZRxyY8Ksw\n" +
"HwYDVR0jBBgwFoAUyWi/jZwB6vyUp0Uby+n0CIcIvPQwgZ4GCCsGAQUFBwEBBIGR\n" +
"MIGOMEIGCCsGAQUFBzABhjZodHRwOi8vb2NzcC5nbG9iYWxzaWduLmNvbS9hbHBo\n" +
"YXRlY2hub2xvZ2llc3Jvb3RjYTIwMjMwSAYIKwYBBQUHMAKGPGh0dHA6Ly9zZWN1\n" +
"cmUuZ2xvYmFsc2lnbi5jb20vYWxwaGF0ZWNobm9sb2dpZXNyb290Y2EyMDIzLmNy\n" +
"dDBKBgNVHR8EQzBBMD+gPaA7hjlodHRwOi8vY3JsLmdsb2JhbHNpZ24uY29tL2Fs\n" +
"cGhhdGVjaG5vbG9naWVzcm9vdGNhMjAyMy5jcmwwDQYJKoZIhvcNAQELBQADggEB\n" +
"AB6liV6fu4knyDFTtJ14pXbuRtDTOtMpQwDfuPBsRKOXzwDQNsrDiAkH4C/RB2eu\n" +
"P1D5ltVqUMsTOHEwOJgz108oGnmrVzXzeqv3qjzzLV7iNIj8fXip8iwaKJ+VYgsj\n" +
"ilVLFjWdv/mnSO9VSjDRu0VUPNQoXy7tTRPgblBKQdIhvF9wtQk86FQmiPTOBCWr\n" +
"o097ZOwmQIBjj/RR9AEL2n6u/r8Hig/7GNFdtOD1VYGjK6AhY7JUxbkKKP0hY7LB\n" +
"xmRX9y21ZAZT7mjKhdUwCleCIn96wbM2kS7UV24ZQ1ouQuzbCzQlb2UwsMPgZ0G1\n" +
"dzYf847TuM1T07jXUnE7AUM=\n" +
"-----END CERTIFICATE-----";


    
}
